emotes = {
    "lets out a savage roar.",
    "slams her weapon to the earth.",
    "howls like a beast unchained.",
    "beats her chest with her weapon hilt.",
    "laughs like a berserker as the scent of blood fills the air.",
    "kicks dust skyward and snarls with savage fury.",
    "raises her weapon high.",
    "growls a deep war-chant.",
    "roars a brutal challenge.",
    "stomps the ground.",
    "howls skyward.",
    "stomps in rhythm.",
    "bellows to the wind.",
    "streaks blood across her face.",
    "snaps her fingers, sparks fly, as a grin spreads across her face.",
    "pounds her chest with both fists.",
    "throws her head back and howls.",
    "radiates unshakable fury.",
    "shakes with fury, eyes blazing under warpaint.",
    "digs her boots in and howls with iron resolve.",
    "swings her weapon in a wide arc.",
    "slams her weapon into stone, splinters flying with each blow.",
    "lets her weapon hum with fury.",
    "bangs her weapon on iron plates.",
    "points her weapon forward, inspiring those around her.",
    "spins her weapon with one hand, letting the wind scream through it.",
    "taps her weapon against her thigh like a war drum.",
    "raises her weapon with a grunt, rallying for the first strike.",
    "snaps her weapon into both hands, grinning ear to ear.",
    "throws her weapon up, catches it mid-spin, and laughs.",
    "leans into her weapon with a low growl, daring anyone to charge.",
    "lifts her weapon to the sky, catching lightning in her eyes.",
    "slashes the air in front of her, then roars with glee.",
    "holds her weapon to her heart, then slams it down at her feet.",
    "scrapes her weapon across her armor, sparks flying before the storm.",
    "cackles as a stick of dynamite hisses in her hand.",
    "pulls a lever, fireworks erupt as her war cry shakes the sky.",
    "grins wide as a fuse burns down her gauntlet.",
    "stands in the smoke, laughing as chaos erupts.",
    "slams a metal charge into the ground, causing sparks to erupt.",
    "ignites a powder trail with her boot and grins as it hisses forward.",
    "juggles three grenades for a heartbeat before flinging them all.",
    "lets her belt-mounted launcher cough smoke as she laughs.",
    "slaps a rune charge against a wall and sprints off, howling.",
    "sparks fly from her fingers as she touches exposed wire.",
    "slams an ignition crystal into a shell and lobs it into battle.",
    "strikes steel against flint and watches the flames spread.",
    "kicks over a crate marked "volatile" and grins at the noise.",
    "snarls as raw fury crackles off her armor like static.",
    "slams her boots down the air thickens with bloodlust.",
    "lets out a warcry that sharpens every nearby weapon.",
    "draws in a breath so deep it pulls the rage from the sky.",
    "stands firm and doubt dies.",
    "pounds her chest.",
    "grips her weapon.",
    "lets her rage roll through the ranks like thunder.",
    "flares with rage, blades start to hum.",
    "plants her feet.",
    "cracks her neck.",
    "unleashes a pulse of power that grips every warrior's spine.",
    "lets the roar of war tear into her kin.",
    "erupts with dominance.",
    "brims with fury so thick the air tastes like blood.",
    "lets her presence ignite the rage in every warrior nearby.",
    "thunders forward.",
    "stands tall, every fighter around her strikes harder.",
    "cracks her knuckles, blades around her gleam with fury.",
    "raises her weapon, the air thickens with warlust.",
    "howls with force so primal it strengthens everyone's heart.",
    "stomps the ground and sets off a ripple of raw aggression.",
    "radiates fury so wild that the timid turn bold.",
    "channels her rage the MadAxeClan roars as one.",
    "shakes the battlefield with a shout.",
    "beats her chest, as every axe nearby swings heavier.",
    "unleashes such fury that even the calm start screaming.",
    "drives her will into the air and the air answers.",
    "steps forward, the front line surges with strength.",
    "tenses her muscles, as everyone tightens their grip.",
    "calls the storm through her veins.",
    "lets her fury flow, as even the earth seems ready to strike.",
    "erupts with presence and all hesitation burns away.",
    "ignites a fire so fierce it spreads through every heart.",
    "lashes the spirit of war into her kin with one brutal shout.",
}

builtInEmotes = { "CHARGE", "ROAR", "FLEX", "CHEER", "LAUGH" }
