yellEmotes = {
    "MadAxeClan CHARGES FIRST!",
    "WE fight where WE stand!",
    "NO mercy. NO pause.",
    "Axes BEFORE talk!",
    "MAKE 'em REMEMBER!",
    "TAKE the fight you FIND!",
    "STRIKE first. STRIKE LOUD!",
    "MadAxeClan NEVER WAITS!",
    "If it AIN'T us, TEST its spine!",
    "Come back LOUDER!",
    "NO safe zones!",
    "DUST, BLOOD, and FIRE!",
    "Paint it RED!",
    "Axes OUT, doubts GONE!",
    "FOR the Clan!",
    "FIGHT LOUD. DIE PROUD.",
    "MadAxeClan!",
    "CRACK 'em! BREAK 'em! BURN 'em!",
    "We BRING the BATTLE!",
    "LEAVE NONE STANDING!",
    "BRACE yourselves, OR DON'T!",
    "FUSES are SHORT, light 'em or RUN!",
    "The SQUIRREL wants FIRE!",
    "SQUIRREL'S got MORE KILLS than HALF the camp!",
    "FOLLOW the MAD ONE!",
    "That SQUIRREL just INSULTED their ANCESTORS!",
    "BURN IT, CHEW IT, BLOW IT UP!",
    "WE RAGE!!",
    "CUT and COMBUST!",
    "Let the WORLD EXPLODE!",
    "BOOM comes BEFORE MERCY!",
    "Let's MAKE FIREWORKS!",
    "LIGHT 'EM ALL UP!",
    "FEEL the TICKING of FATE!",
    "LIGHT IT ALL!",
    "Who wants SOMETHING UNSTABLE?!",
    "INCOMING CHAOS!",
    "FOR OUR WAR-CHIEF!",
    "ORCISH BLOOD NEVER YIELDS!",
    "STRIKE HARD! No cowards in the HORDE!",
    "STAND AND FIGHT!",
    "CARVE your PATH in BLOOD!",
    "THIS EDGE ENDS LIVES!",
    "Let's MAKE ART!",
    "UNLEASH YOUR WRATH!",
    "The HORDE STANDS THROUGH IT ALL!",
    "Even the MOUNTAIN BREAKS!",
    "NO BRAKES. NO FEAR.",
    "Their BLOOD SINGS LOUDER THAN DRUMS!",
    "It's SLAUGHTER TIME!",
    "NOW WE BURN THEM DOWN!",
    "MadAxeClan doesn't back down!",
    "First in loudest out!",
    "Make 'em FEEL it!",
    "We don't warn, we STRIKE!",
    "Shout loud, kill louder!",
    "Too late to beg now!",
    "SPILLBLOOD!",
    "Raise hell, raise axes!",
    "We burn the weak!",
    "Hit first, ask NEVER!",
    "Rage first, regret nothing!",
    "No step back. Not one.",
    "MadAxeClan fights FIRE with FIRE!",
    "Your screams are our drumbeat!",
    "Our fury needs no reason!",
    "Axes, blood, and broken bones!",
    "If it stands, it falls!",
    "Laugh as you swing!",
    "Die louder than they cry!",
    "Fight like it's your last breath!",
    "I'LL SHOUT TILL YOUR BONES RATTLE!",
    "I'M NOT YELLING, THIS IS FOREPLAY!",
    "YOUR FACE LOOKS BETTER WITH AN AXE IN IT!",
    "I'LL LICK THE ASHES OFF YOUR BONES!",
    "NEXT ONE TO FALL GETS A KISS!",
    "I DON'T NEED A REASON, I NEED A TARGET!",
    "I BITE HARDER THAN YOU HIT!",
    "FIGHT HARDER!",
    "CRUSH THEM!",
    "MAKE IT BLEED!",
    "BREAK THEIR LINES!",
    "HIT LIKE YOU MEAN IT!",
    "NO MERCY JUST BLOOD!",
    "STRIKE FOR THE HORDE!",
    "FIGHT FOR MADAXECLAN!",
    "GRIND THEM DOWN!",
    "BE ROUGH!",
}
